[paths]
shared_data = ../shared-data/data
source_data = data/source_data
results_path = data/results

base_prefix = vdl_project_template


relevance_model_predictions_parent_dir = {shared_data}/models/MODEL_NAME_HOLDER
relevance_model_predictions_path = {relevance_model_predictions_parent_dir}/predictions.jsonl
# Assuming VIBRANT DATA LABS relevance model
relevance_model_predictions_label_override_path = {relevance_model_predictions_parent_dir}/conservative_relevant_labels_082024.json

one_earth_taxonomy = {shared_data}/taxonomies/oneearth/OE Solutions Terms 20250306_expanded.xlsx
one_earth_taxonomy_mapping_results = {results_path}/one_earth_taxonomy_mapping_results.json
oe_tax_mapping_distributed_funding_results = {results_path}/one_earth_taxonomy_mapping_distributed_funding_results.json

tailwind_taxonomy = {shared_data}/taxonomies/tailwind/Tailwind_Themes_Sectors.xlsx
tailwind_taxonomy_mapping_results = {results_path}/tailwind_taxonomy_mapping_results.json
tw_tax_mapping_distributed_funding_results = {results_path}/tw_tax_mapping_distributed_funding_results.json

embedding_clus = {results_path}/embedding_clusters

player_path = {results_path}/player
player_dir = {player_path}/player
player_attribute_settings = {base_prefix}/player_building/player_attribute_settings.xlsx

nw_name = {player_path}/{base_prefix}_network.json
nw_name_cleaned = {player_path}/{base_prefix}_network_cleaned.json

processed_data_path = {results_path}/processed_data.json
source_data_path = {source_data}/lenders.json
enriched_data_path = {results_path}/enriched_data.json